# Generated by Django 5.2.7 on 2025-10-23 03:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ride', '0002_alter_ride_dropoff_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='pickup_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 10, 23, 3, 35, 13, 624234, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
