# Generated by Django 5.2.7 on 2025-10-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ride', '0003_alter_ride_pickup_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='distance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
