# Generated by Django 5.2.7 on 2025-10-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ride', '0004_ride_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='distance',
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('en-route', 'En-route'), ('pickup', 'Pickup'), ('dropoff', 'Dropoff')], default='pickup', max_length=10),
        ),
    ]
