# Generated by Django 5.2.7 on 2025-10-22 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ride', '0002_alter_ride_dropoff_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideEvent',
            fields=[
                ('id_ride_event', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ride.ride')),
            ],
            options={
                'verbose_name': 'RideEvent',
                'verbose_name_plural': 'RideEvents',
            },
        ),
    ]
