# Generated by Django 5.2.7 on 2025-10-23 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ride', '0003_alter_ride_pickup_time'),
        ('RideEvent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rideevent',
            name='id_ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_events', to='Ride.ride'),
        ),
    ]
