# Generated by Django 5.2.7 on 2025-10-23 08:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideEvent', '0002_alter_rideevent_id_ride'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rideevent',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
