# Generated by Django 5.2.7 on 2025-10-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('rider', 'Rider'), ('driver', 'Driver')], default='rider', max_length=10),
        ),
    ]
