# Generated by Django 5.2.7 on 2025-10-23 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id_ride',
            new_name='id_user',
        ),
    ]
